config:
  send_anonymous_usage_stats: False

transform:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: warehouse_db
      port: 5432
      user: warehouse
      pass: warehouse1234
      dbname: warehouse_db
      schema: warehouse